### ISSUE TITLE
Unable to open link to commit from event

### ISSUE THREAD

**Issue by Mikoj** [thedillonb/CodeBucket#12] opened 2016-02-11 18:07 UTC
On event page click commit and get this ![](http://i.imgur.com/yJFQ2et.jpg)

**Comment by thedillonb** [comment] 2016-02-11 19:35
Hey @Mikoj, I'm unable to reproduce this. Walk me through your process:

1. You go to the "Events" view
2. You click on a commit (A assume you click on the hash?)
3. You receive this error message?

**Comment by Mikoj** [comment] 2016-02-11 19:49
exactly on event view click commit hash and receive this error.

**Comment by thedillonb** [comment] 2016-07-27 13:12
Cleaning up this ticket as Mikoj has already submitted a PR, and merged, a fix for this.

**Closed by thedillonb** 2016-07-27 13:12 UTC
